import Head from 'next/head'
import { Inter } from '@next/font/google'
import Image from 'next/image'

const inter = Inter({ subsets: ['latin'] })

export default function About() {
    return (
    <>
    <Head>
        <title>Ciimnuai</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <main>
        <div class="container mx-auto flex flex-col md:flex-row items-center my-12 md:my-24">
            <div class="flex flex-col w-full lg:w-1/2 justify-center items-start pt-12 pb-24 px-6 text-justify">
                <h1 class="font-bold text-3xl my-4">About</h1>
                <p class="leading-normal mb-4">
                As stated on the landing page, the purpose of this website is to preserve and protect the rich cultural heritage and traditions of the Zomi people, which have been gradually fading away among younger generations. The website showcases the cultures, traditions, and languages of a people who once thrived in the city of Ciimnuai. Sadly, these people are now scattered across the globe and are native to many different countries, making it increasingly challenging for the new generation to connect with their roots and maintain their cultural identity. With this in mind, the website was created to offer an overview of their history and background.
                </p>
                <p class="leading-normal mb-4">
                    Zomi te ih citawm ban ah mun tuamtaum ah ki thehthang mang ih hih man in, ih ngeina leh ih paizia te kepcing ding leh theihtel ding ong haksa semsem ta hi. A diakdiak in khangthak Zomi te in ih pau leh ham zong ki kemcing zo nawnlo mai hi. Tua te kawmkal ah ih ngeina leh ih thangthu a kepcinghuai mahmah pawlkhat zong ong mangthang dekdek ta hi. Hih teng ngaihsutna tawh website ong ki bawl khia hi in, kim tom cing in Cimmnuai vontawi Zomi te ngeina leh tangthu ki cian khahna ding in a ki gel a hihi.
                </p>
                {/* <p class="leading-normal mb-4">
                    Hanciamna tawh a ki bawl a hih man in theihsak nop tuamtuam a om leh admin@ciimnuai.com.
                </p> */}
            </div>
            <div class="w-full lg:w-1/2 lg:py-6 text-center">
                <img class='rounded-lg w-full' src='/imgs/tedim-hill.jpeg' alt='Tedim hill'/>
            </div>
        </div>
    </main>
    </>
    )
}
