import Head from 'next/head'
import { Inter } from '@next/font/google'
import Image from 'next/image'

const inter = Inter({ subsets: ['latin'] })

export default function Extra() {
    return (
    <>
    <Head>
        <title>Ciimnuai</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <main>
        <div class="container mx-auto flex flex-col md:flex-row items-center my-12 md:my-24">
            <div class="flex flex-col w-full lg:w-2/3 justify-center items-start pt-12 pb-24 px-6 text-justify">
                <h1 class="font-bold text-3xl my-4">Relevant websites</h1>
                <p class="leading-normal mb-4">
                    <a class='underline font-bold' href='http://www.zogam.org/' target='_blank'>Zogam</a> - Thutuamtuam kicing a postna
                </p>
                <p class="leading-normal mb-4">
                    <a class='underline font-bold' href='https://zomidaily.org/' target='_blank'>Zomi daily</a> - News leh thudang tuamtuam postna
                </p>
                <p class="leading-normal mb-4">
                    <a class='underline font-bold' href='http://zomilibrary.com/' target='_blank'>Zogam library</a> - Laibu tuamtuam kepcingna
                </p>
                <p class="leading-normal mb-4">
                    <a class='underline font-bold' href='https://www.tongdot.com/' target='_blank'>Tongdot</a> - Pau khiatna (dictionary) lam tawh kisai
                </p>
                <p class="leading-normal mb-4">
                    <a class='underline font-bold' href='https://www.zaideih.com/' target='_blank'>Zaideih</a> - La leh music lam tawh kisai
                </p>
            </div>
        </div>
    </main>
    </>
    )
}
