import Head from 'next/head'
import { Inter } from '@next/font/google'
import fs from 'fs';
import path from 'path';
import Image from 'next/image';
import { useState, useEffect } from 'react';


const inter = Inter({ subsets: ['latin'] })

export default function Gallery({ images }) {
    const [selectedImage, setSelectedImage] = useState(null);

    const handleClick = (image) => {
        setSelectedImage(image);
    };

    const handleClose = () => {
        setSelectedImage(null);
    };

    useEffect(() => {
        if (selectedImage) {
          document.body.style.overflow = 'hidden';
        } else {
          document.body.style.overflow = 'unset';
        }
    
        return () => {
          document.body.style.overflow = 'unset';
        };
      }, [selectedImage]);

    return (
        <>
            <Head>
                <title>Ciimnuai</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <div class="container mx-auto flex flex-col md:flex-row items-center my-12 md:my-24">
                    {/* <div className="grid grid-cols-3 gap-4">
                        {images.map((image) => (
                            <img key={image} src={`/imgs/zomi-related/${image}`} alt="" class="w-full h-full object-cover"/>
                        ))}
                    </div> */}
                    <div className="grid grid-cols-3 gap-4">
                        {images.map((image) => (
                            <div key={image} className="flex items-center justify-center">
                                <img
                                    src={`/imgs/zomi-related/${image}`}
                                    alt=""
                                    className="w-full h-full object-cover cursor-pointer"
                                    style={{ width: '100%' }}
                                    onClick={() => handleClick(image)}
                                />
                            </div>
                        ))}
                    </div>
                </div>
                {selectedImage && (
                    <div className="fixed top-0 left-0 w-full h-full bg-black bg-opacity-75 flex items-center justify-center" onClick={handleClose} >
                        <div className="bg-white rounded-lg overflow-hidden" onClick={(e) => e.stopPropagation()} >
                            <img src={`/imgs/zomi-related/${selectedImage}`} alt="modal" />
                        </div>
                    </div>
                )}
            </main>
        </>
    )
}

export async function getStaticProps() {
    const imageDirectory = path.join(process.cwd(), 'public', 'imgs', 'zomi-related');
    const filenames = fs.readdirSync(imageDirectory);
    const images = filenames
        .filter((name) => /\.(jpg|jpeg|png|gif)$/i.test(name))
        .map((name) => `/${name}`);

    return { props: { images } };
}
